### ISSUE TITLE
The code crashes the emulator 

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Cryogenic#1]
After a Grp5 instruction.
The DOSInt21Handler is asked for a service at index 0
It doesn't exist -> exception -> crash.

Doesn't happen in the Java original, with or without running overrides from CryoDuneRE.

**Comment by maximilien-noal** [comment]
Also neither does the call for the service at index 0, neither the crash happen with the emulator alone (: without cryogenic injecting any code)

It also doesn't happen if --UseCodeOverrides is not specified.

**Comment by kevinferrare** [comment]
Fixed in spice86 with commit https://github.com/OpenRakis/Spice86/commit/951894aa3595a42078eebefd11b8be8f09e1576d !
The emulator was not calling what the override was returning and this was causing anything overridden to be called twice.
