### ISSUE TITLE
No music on GNU/Linux

### ISSUE THREAD

**Issue by leorockway** [OpenRakis/Cryogenic#29]
When I try to run this on GNU/Linux following the README instructions I get this error:

`/usr/share/dotnet/sdk/8.0.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(154,5): error NETSDK1083: The specified RuntimeIdentifier 'linux-ADL220 SBP2227' is not recognized. See https://aka.ms/netsdk1083 for more information. [/home/leo/Cryogenic/src/Cryogenic/Cryogenic.csproj]
/usr/share/dotnet/sdk/8.0.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(154,5): error NETSDK1083: The specified RuntimeIdentifier 'linux-ADL220 SBP2227' is not recognized. See https://aka.ms/netsdk1083 for more information. [/home/leo/Cryogenic/src/Cryogenic/Cryogenic.csproj]
/usr/share/dotnet/sdk/8.0.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(154,5): error NETSDK1083: The specified RuntimeIdentifier 'linux-ADL220 SBP2227' is not recognized. See https://aka.ms/netsdk1083 for more information. [/home/leo/Cryogenic/src/Cryogenic/Cryogenic.csproj]
/usr/share/dotnet/sdk/8.0.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(154,5): error NETSDK1083: The specified RuntimeIdentifier 'linux-ADL220 SBP2227' is not recognized. See https://aka.ms/netsdk1083 for more information. [/home/leo/Cryogenic/src/Cryogenic/Cryogenic.csproj]`

The build failed. Fix the build errors and run again`

I'm not sure what would be a correct RuntimeIdentifier.

**Comment by maximilien-noal** [comment]
Hello,

Thanks for the report. I fixed it:

    cd Cryogenic/src/Cryogenic
    dotnet publish
    bin/Release/net8.0/publish/Cryogenic --Exe C:/path/to/dunecd/DNCDPRG.EXE --UseCodeOverride true -a "ADL220 SBP2227"
